config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :shops do
    devise_for :shops, controllers: {
      registrations: 'shops/registrations',
      sessions: 'shops/sessions'
    }
  end

  scope module: :customers do
    devise_for :customers, controllers: {
      registrations: 'customers/registrations',
      sessions: 'customers/sessions'
    }
  end

  namespace :shops do
    get 'orders/search' => 'orders#search'
    resources :orders, only: %i[show index update]
    resources :customers, only: %i[index show]
    resource :mypages, only: %i[show edit update]
    get 'items/search' => 'items#search'
    resources :items, except: [:destroy]
    resources :reviews, only: [:show]
    get 'homes' => 'homes#top'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'shops/search' => 'shops#search'
    resources :shops, only: %i[index show]
    resources :rooms, only: %i[index show create] do
      resources :messages, only: [:create]
    end
    resources :reviews, only: %i[create destroy show]
    resources :favorites, only: %i[index create destroy]
    get 'orders/complete'
    resources :orders, only: %i[new create index show]
    delete 'cart_items/empty'
    resources :cart_items, only: %i[index update destroy create]
    resource :mypages, only: %i[show edit update]
    get 'items/search' => 'items#search'
    resources :items, only: %i[show index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :store_name, presence: true
  validates :store_manager, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :phone_number, presence: true
end

app/models/shop.rb
# frozen_string_literal: true

class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :shop_image
  
  def self.search(keyward)
    if keyward
      Shop.where('shop_name LIKE ? OR introduction LIKE ?', "%#{keyward}%",
                  "%#{keyward}%")
    else
      Shop.none
    end
  end
  
  def self.select(shop_genre)
    if shop_genre
      Shop.where(shop_genre: shop_genre)
    else
      Shop.all
    end
  end

  has_many :items, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :shop_name, presence: true
  validates :manager, presence: true
  validates :shop_genre, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :phone_number, presence: true
  enum shop_genre: [
    '食肉',
    '水産',
    '野菜・青果',
    'その他'
  ]
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

module Customers
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
                                        keys: %i[store_name store_manager address postal_code phone_number])
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    def after_sign_up_path_for(_resource)
      mypages_path
    end
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

module Customers
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end

    def after_sign_in_path_for(_resource)
      mypages_path
    end
  end
end

app/controllers/shops/customers_controller.rb
# frozen_string_literal: true

module Shops
  class CustomersController < ShopsController
    def index
      orders = Order.where(shop_id: current_shop.id)
      ordered_customers = []
      orders.each do |order|
        ordered_customers << order.customer
      end
      @customers = ordered_customers.uniq
    end

    def show
      @customer = Customer.find(params[:id])
      @reviews = Review.where(customer_id: params[:id], shop_id: current_shop.id).page(params[:page]).per(10).order(created_at: 'DESC')
      @room = Room.find_by(shop_id: current_shop.id, customer_id: params[:id])
    end
  end
end

app/controllers/shops/homes_controller.rb
# frozen_string_literal: true

module Shops
  class HomesController < ShopsController
    layout 'shop_top'
    
    def top; end
  end
end

app/controllers/shops/items_controller.rb
# frozen_string_literal: true

module Shops
  class ItemsController < ShopsController
    before_action :set_item, only: %i[show edit update]

    def index
      @items = if params[:item_genre]
                 Item.where(item_genre: params[:item_genre], shop_id: current_shop.id).page(params[:page]).per(15).order(created_at: 'DESC')
               else
                 Item.where(shop_id: current_shop.id).page(params[:page]).per(15).order(created_at: 'DESC')
               end
    end

    def search
      if params[:keyward].present?
        items = Item.where('item_name LIKE ?', "%#{params[:keyward]}%")
        @items = items.where(shop_id: current_shop.id).page(params[:page]).per(15).order(created_at: 'DESC')
      else
        @items = Item.none
      end
    end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new(item_params)
      @item.shop_id = current_shop.id
      if @item.save
        redirect_to shops_item_path(@item.id), notice: '商品を登録しました。'
      else
        render :new
      end
    end

    def show; end

    def edit; end

    def update
      if @item.update(item_params)
        redirect_to shops_item_path(@item.id), notice: '商品情報を変更しました。'
      else
        render :edit
      end
    end

    private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(
        :item_name,
        :item_genre,
        :item_image,
        :item_introduction,
        :item_price,
        :sale_status
      )
    end
  end
end

app/controllers/shops/mypages_controller.rb
# frozen_string_literal: true

module Shops
  class MypagesController < ShopsController
    def show; end

    def edit
      @shop = current_shop
    end

    def update
      @shop = current_shop
      if @shop.update(shop_params)
        redirect_to shops_mypages_path, notice: '会員情報を変更しました。'
      else
        render :edit
      end
    end

    private

    def shop_params
      params.require(:shop).permit(
        :shop_name,
        :manager,
        :introduction,
        :shop_image,
        :shop_genre,
        :adddress,
        :postal_code,
        :phone_number,
        :email
      )
    end
  end
end

app/controllers/shops/orders_controller.rb
# frozen_string_literal: true

module Shops
  class OrdersController < ShopsController
    before_action :set_order, only: [:show, :update]
    def show
      @order_items = OrderItem.where(order_id: @order.id)
    end

    def index
      @orders = if params[:delivery_status]
                  Order.where(delivery_status: params[:delivery_status],
                              shop_id: current_shop.id).page(params[:page]).per(10).order(created_at: 'DESC')
                elsif params[:customer_id]
                  Order.where(customer_id: params[:customer_id], shop_id: current_shop.id).page(params[:page]).per(10).order(created_at: 'DESC')
                else
                  Order.where(shop_id: current_shop.id).page(params[:page]).per(10).order(created_at: 'DESC')
                end
    end
    
    def search
      @orders = if params[:keyward].present?
                  if customer = Customer.find_by('store_name LIKE ?', "%#{params[:keyward]}%")
                    customer.orders.where(shop_id: current_shop.id).page(params[:page]).per(10).order(created_at: 'DESC')
                  else
                    Order.none
                  end
                else
                    Order.none
                end
    end

    def update
      @order.update(order_params)
      redirect_to shops_order_path(@order.id), notice: '配送ステータスを更新しました。'
    end

    private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:delivery_status)
    end
  end
end

app/controllers/shops/registrations_controller.rb
# frozen_string_literal: true

module Shops
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters
    layout 'shop_top'
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
                                        keys: %i[shop_name manager shop_genre postage address postal_code phone_number])
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    def after_sign_up_path_for(_resource)
      shops_mypages_path
    end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/shops/sessions_controller.rb
# frozen_string_literal: true

module Shops
  class SessionsController < Devise::SessionsController
    layout 'shop_top'
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end

    def after_sign_in_path_for(_resource)
      shops_mypages_path
    end

    def after_sign_out_path_for(_resouce)
      shops_homes_path
    end
  end
end

app/controllers/shops_controller.rb
# frozen_string_literal: true

class ShopsController < ApplicationController
  before_action :authenticate_shop!, except: [:top]
end

app/helpers/shops/customers_helper.rb
# frozen_string_literal: true

module Shops
  module CustomersHelper
  end
end

app/helpers/shops/homes_helper.rb
# frozen_string_literal: true

module Shops
  module HomesHelper
  end
end

app/helpers/shops/items_helper.rb
# frozen_string_literal: true

module Shops
  module ItemsHelper
  end
end

app/helpers/shops/mypages_helper.rb
# frozen_string_literal: true

module Shops
  module MypagesHelper
  end
end

app/helpers/shops/orders_helper.rb
# frozen_string_literal: true

module Shops
  module OrdersHelper
  end
end

app/helpers/shops/reviews_helper.rb
# frozen_string_literal: true

module Shops
  module ReviewsHelper
  end
end

app/views/shops/customers/index.html.erb
<div class="container-fluid">
  <div class="form-box col-lg-10 mx-auto">
    <h3 class="page-title">顧客一覧</h3>
     <% @customers.each do |customer| %>
      <div class="shop-contents border-bottom">
        <%= link_to shops_customer_path(customer.id) do %>
          <div class="shop-info row">
            <div class="col-md-3">
              <label>店舗名：</label>
              <%= customer.store_name %>
            </div>
            <div class="col-md-6">
              <label>住所：</label>
              <%= customer.address %>
            </div>
            <div class="col-md-3">
              <label>電話番号：</label>
              <%= customer.phone_number %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/customers/show.html.erb
<div class="container-fluid">
  <div class="form-box">
    <div class="row">
      <div class="col-lg-6">
        <h3 class="page-title"><%= "#{@customer.store_name}様のプロフィール"%></h3>
        <div class="info-group row">
          <div class="col-md-4">
            <label class="info-label">店舗名</label>
          </div>
          <div class="col-md-8">
            <%= @customer.store_name %>
          </div>
        </div>
        <div class="info-group row">
          <div class="col-md-4">
            <label class="info-label">責任者氏名</label>
          </div>
          <div class="col-md-8">
            <%= @customer.store_manager %>
          </div>
        </div>
        <div class="info-group row">
          <div class="col-md-4">
            <label class="info-label">郵便番号</label>
          </div>
          <div class="col-md-8">
            <%= @customer.postal_code %>
          </div>
        </div>
        <div class="info-group row">
          <div class="col-md-4">
            <label class="info-label">住所</label>
          </div>
          <div class="col-md-8">
            <%= @customer.address%>
          </div>
        </div>
        <div class="info-group row">
          <div class="col-md-4">
            <label class="info-label">電話番号</label>
          </div>
          <div class="col-md-8">
            <%= @customer.phone_number%>
          </div>
        </div>
        <div class="info-group row">
          <div class="col-md-4">
            <label class="info-label">メールアドレス</label>
          </div>
          <div class="col-md-8">
            <%= @customer.email%>
          </div>
        </div>
        <div>
          <%= link_to "注文一覧を見る", shops_orders_path(customer_id: params[:id]), class: "btn btn-warning m-2" %>
          <% if @room %>
            <p class="m-2"><%= link_to "チャットルームへ移動", room_path(@room), class: "btn green-btn" %></p>
          <% else %>
            <%= form_with model: Room.new, local: true, class: "m-2" do |f| %>
              <%= f.hidden_field :customer_id, value: params[:id] %>
              <%= f.submit "メッセージを送る", class: "btn green-btn" %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-lg-6">
        <h3 class="page-title"><%= "#{@customer.store_name}様のレビュー"%></h3>
        <div class="reviews">
          <% if @reviews.present? %>
            <% @reviews.each do |review| %>
              <div class="row info-group">
                <div class="col-lg-5">
                  <div id="star" class="read-only-star" data-score="<%= review.rate%>"></div>
                </div>
                <div class="col-lg-4">
                  <%= review.created_at.to_s(:datetime) %>
                </div>
                <div class="col-lg-3">
                  <%= link_to review.content.truncate(10), review_path(review.id) %>
                </div>
              </div>
            <% end %>
            <div class="col-12 d-flex justify-content-center">
            <%= paginate @reviews %>
          </div>
          <% else %>
              <p class="no-review">まだレビューがありません</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('.read-only-star').empty();
    $('.read-only-star').raty({
      readOnly: true,
      half: true,
      size: 36,
      starOff: "<%= asset_path('star-off.png') %>",
      starOn: "<%= asset_path('star-on.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      score: function () {
        return $(this).attr('data-score');
      }
    });
</script>