config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :shops do
    devise_for :shops, controllers: {
      registrations: 'shops/registrations',
      sessions: 'shops/sessions'
    }
  end

  scope module: :customers do
    devise_for :customers, controllers: {
      registrations: 'customers/registrations',
      sessions: 'customers/sessions'
    }
  end

  namespace :shops do
    get 'orders/search' => 'orders#search'
    resources :orders, only: %i[show index update]
    resources :customers, only: %i[index show]
    resource :mypages, only: %i[show edit update]
    get 'items/search' => 'items#search'
    resources :items, except: [:destroy]
    resources :reviews, only: [:show]
    get 'homes' => 'homes#top'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'shops/search' => 'shops#search'
    resources :shops, only: %i[index show]
    resources :rooms, only: %i[index show create] do
      resources :messages, only: [:create]
    end
    resources :reviews, only: %i[create destroy show]
    resources :favorites, only: %i[index create destroy]
    get 'orders/complete'
    resources :orders, only: %i[new create index show]
    delete 'cart_items/empty'
    resources :cart_items, only: %i[index update destroy create]
    resource :mypages, only: %i[show edit update]
    get 'items/search' => 'items#search'
    resources :items, only: %i[show index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  attachment :item_image

  def tax
    1.1
  end

  def tax_price
    (item_price * tax).floor
  end

  def self.search(keyward)
    if keyward
      Item.where('item_name LIKE ? OR item_introduction LIKE ?', "%#{keyward}%",
                  "%#{keyward}%")
    else
       Item.none
    end
  end

  def self.select(item_genre, shop_id)
    if item_genre && shop_id
       Item.where(item_genre: item_genre, shop_id: shop_id)
    elsif item_genre
       Item.where(item_genre: item_genre)
    elsif shop_id
       Item.where(shop_id: shop_id)
    else
       Item.all
    end
  end

  belongs_to :shop

  has_many :cart_items
  has_many :order_items

  validates :item_name, presence: true
  validates :item_price, presence: true
  validates :item_genre, presence: true
  validates :item_introduction, presence: true

  enum item_genre: %w[
    食肉
    食肉加工品
    魚介
    魚介加工品
    青果
    野菜
    調味料
    その他
  ]
end

app/models/shop.rb
# frozen_string_literal: true

class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :shop_image
  
  def self.search(keyward)
    if keyward
      Shop.where('shop_name LIKE ? OR introduction LIKE ?', "%#{keyward}%",
                  "%#{keyward}%")
    else
      Shop.none
    end
  end
  
  def self.select(shop_genre)
    if shop_genre
      Shop.where(shop_genre: shop_genre)
    else
      Shop.all
    end
  end

  has_many :items, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :shop_name, presence: true
  validates :manager, presence: true
  validates :shop_genre, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :phone_number, presence: true
  enum shop_genre: [
    '食肉',
    '水産',
    '野菜・青果',
    'その他'
  ]
end

app/controllers/shops/customers_controller.rb
# frozen_string_literal: true

module Shops
  class CustomersController < ShopsController
    def index
      orders = Order.where(shop_id: current_shop.id)
      ordered_customers = []
      orders.each do |order|
        ordered_customers << order.customer
      end
      @customers = ordered_customers.uniq
    end

    def show
      @customer = Customer.find(params[:id])
      @reviews = Review.where(customer_id: params[:id], shop_id: current_shop.id).page(params[:page]).per(10).order(created_at: 'DESC')
      @room = Room.find_by(shop_id: current_shop.id, customer_id: params[:id])
    end
  end
end

app/controllers/shops/homes_controller.rb
# frozen_string_literal: true

module Shops
  class HomesController < ShopsController
    layout 'shop_top'
    
    def top; end
  end
end

app/controllers/shops/items_controller.rb
# frozen_string_literal: true

module Shops
  class ItemsController < ShopsController
    before_action :set_item, only: %i[show edit update]

    def index
      @items = if params[:item_genre]
                 Item.where(item_genre: params[:item_genre], shop_id: current_shop.id).page(params[:page]).per(15).order(created_at: 'DESC')
               else
                 Item.where(shop_id: current_shop.id).page(params[:page]).per(15).order(created_at: 'DESC')
               end
    end

    def search
      if params[:keyward].present?
        items = Item.where('item_name LIKE ?', "%#{params[:keyward]}%")
        @items = items.where(shop_id: current_shop.id).page(params[:page]).per(15).order(created_at: 'DESC')
      else
        @items = Item.none
      end
    end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new(item_params)
      @item.shop_id = current_shop.id
      if @item.save
        redirect_to shops_item_path(@item.id), notice: '商品を登録しました。'
      else
        render :new
      end
    end

    def show; end

    def edit; end

    def update
      if @item.update(item_params)
        redirect_to shops_item_path(@item.id), notice: '商品情報を変更しました。'
      else
        render :edit
      end
    end

    private

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(
        :item_name,
        :item_genre,
        :item_image,
        :item_introduction,
        :item_price,
        :sale_status
      )
    end
  end
end

app/controllers/shops/mypages_controller.rb
# frozen_string_literal: true

module Shops
  class MypagesController < ShopsController
    def show; end

    def edit
      @shop = current_shop
    end

    def update
      @shop = current_shop
      if @shop.update(shop_params)
        redirect_to shops_mypages_path, notice: '会員情報を変更しました。'
      else
        render :edit
      end
    end

    private

    def shop_params
      params.require(:shop).permit(
        :shop_name,
        :manager,
        :introduction,
        :shop_image,
        :shop_genre,
        :adddress,
        :postal_code,
        :phone_number,
        :email
      )
    end
  end
end

app/controllers/shops/orders_controller.rb
# frozen_string_literal: true

module Shops
  class OrdersController < ShopsController
    before_action :set_order, only: [:show, :update]
    def show
      @order_items = OrderItem.where(order_id: @order.id)
    end

    def index
      @orders = if params[:delivery_status]
                  Order.where(delivery_status: params[:delivery_status],
                              shop_id: current_shop.id).page(params[:page]).per(10).order(created_at: 'DESC')
                elsif params[:customer_id]
                  Order.where(customer_id: params[:customer_id], shop_id: current_shop.id).page(params[:page]).per(10).order(created_at: 'DESC')
                else
                  Order.where(shop_id: current_shop.id).page(params[:page]).per(10).order(created_at: 'DESC')
                end
    end
    
    def search
      @orders = if params[:keyward].present?
                  if customer = Customer.find_by('store_name LIKE ?', "%#{params[:keyward]}%")
                    customer.orders.where(shop_id: current_shop.id).page(params[:page]).per(10).order(created_at: 'DESC')
                  else
                    Order.none
                  end
                else
                    Order.none
                end
    end

    def update
      @order.update(order_params)
      redirect_to shops_order_path(@order.id), notice: '配送ステータスを更新しました。'
    end

    private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:delivery_status)
    end
  end
end

app/controllers/shops/registrations_controller.rb
# frozen_string_literal: true

module Shops
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters
    layout 'shop_top'
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
                                        keys: %i[shop_name manager shop_genre postage address postal_code phone_number])
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    def after_sign_up_path_for(_resource)
      shops_mypages_path
    end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/shops/sessions_controller.rb
# frozen_string_literal: true

module Shops
  class SessionsController < Devise::SessionsController
    layout 'shop_top'
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end

    def after_sign_in_path_for(_resource)
      shops_mypages_path
    end

    def after_sign_out_path_for(_resouce)
      shops_homes_path
    end
  end
end

app/controllers/shops_controller.rb
# frozen_string_literal: true

class ShopsController < ApplicationController
  before_action :authenticate_shop!, except: [:top]
end

app/helpers/shops/customers_helper.rb
# frozen_string_literal: true

module Shops
  module CustomersHelper
  end
end

app/helpers/shops/homes_helper.rb
# frozen_string_literal: true

module Shops
  module HomesHelper
  end
end

app/helpers/shops/items_helper.rb
# frozen_string_literal: true

module Shops
  module ItemsHelper
  end
end

app/helpers/shops/mypages_helper.rb
# frozen_string_literal: true

module Shops
  module MypagesHelper
  end
end

app/helpers/shops/orders_helper.rb
# frozen_string_literal: true

module Shops
  module OrdersHelper
  end
end

app/helpers/shops/reviews_helper.rb
# frozen_string_literal: true

module Shops
  module ReviewsHelper
  end
end

app/views/shops/items/_index.html.erb
<div class="row">
      <div class="search-box col-lg-3">
        <p>商品名検索</p>
        <%= form_with url: shops_items_search_path, method: :get, class: "row mb-2", local: true do |f| %>
          <%= f.text_field :keyward, class: "col-9 form-control" %>
          <%= f.submit "検索", class: "btn col-3" %>
        <% end %>
        <p>ジャンルから探す</p>
        <p><%= link_to "全て", shops_items_path %></p>
        <%= form_with url: shops_items_path, method: :get, local: true do |f| %>
          <%= f.select :item_genre, Item.item_genres.keys.to_a %>
          <%= f.submit "検索", class: "btn" %>
        <% end %>
      </div>
      <% if @items.empty? %>
        <div class="vh-100 col-lg-9">
          <p>該当の商品がありません</p>
        </div>
      <% else %>
        <div class="col-lg-9 row">
          <% @items.each do |item| %>
            <div class="shop-contents col-md-4 col-sm-6">
              <%= link_to shops_item_path(item.id), class: "row" do %>
                <div class="col-6">
                  <%= attachment_image_tag item, :item_image, fallback: "no_image.jpeg", class: "sm-image" %>
                </div>
                <div class="shop-info col-6 text-center">
                  <p>
                    <%= item.item_name.truncate(15) %>
                  </p>
                  <p>
                    <%= item.tax_price.to_s(:delimited) %>円（税込）
                  </p>
                  <% if item.sale_status %>
                    <p class="text-success">在庫あり</p>
                  <% else %>
                    <p class="text-danger">品切れ</p>
                  <% end %>
                  <p>
                    <%= item.item_introduction.truncate(15) %>
                  </p>
                </div>
              <% end %>
            </div>
          <% end %>
          <div class="col-12 d-flex justify-content-center">
            <%= paginate @items %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shops/items/edit.html.erb
<div class="container-xl">
  <div class="form-box text-center">
    <h3 class="page-title"><%= @item.item_name %>の編集</h3>
    <%= render 'layouts/errors', model: @item %>
    <div class="row">
      <div class="col-lg-6">
        <%= attachment_image_tag @item, :item_image, fallback: "no_image.jpeg", class: "lg-image" %>
      </div>
      <div class="col-lg-6">
        <%= form_with model: @item,url: shops_item_path,local: true do |f| %>
          <div class="form-group row">
            <div class="col">
            <label>
              <i class="fas fa-images btn">商品画像を選択する</i>
              <%= f.attachment_field :item_image, style: "display: none;" %>
            </label>
            </div>
          </div>
          <div class="form-group row">
            <div class="col">
              <%= f.label "商品名", class:"label-form"%>
            </div>
            <div class="col">
              <%= f.text_field :item_name,placeholder:"青森県産　王林", class:"form-control"%>
            </div>
          </div>
          <div class="form-group row">
            <div class="col">
              <%= f.label "ジャンル", class:"label-form"%>
            </div>
            <div class="col">
              <%= f.select :item_genre, Item.item_genres.keys.to_a, {}, class: "form-control" %>
            </div>
          </div>
          <div class="form-group row">
            <div class="col">
              <%= f.label "価格（税抜き）", class:"label-form"%>
            </div>
            <div class="col">
              <%= f.number_field :item_price, class:"form-control"%>
            </div>
          </div>
           <div class="form-group row">
            <div class="col">
              <%= f.label "商品説明", class:"label-form"%>
            </div>
            <div class="col">
              <%= f.text_area :item_introduction, class:"form-control"%>
            </div>
          </div>
          <div class="form-group row">
            <div class="col">
              <%= f.label "販売ステータス", class:"label-form"%>
            </div>
            <div class="col">
              <div>
                <%= f.radio_button :sale_status, :true, checked: true %>
                <%= f.label :sale_status, "在庫あり", class: "d-inline-block" %>
              </div>
              <div>
                <%= f.radio_button :sale_status, :false %>
                <%= f.label :sale_status, "品切れ", class: "d-inline-block" %>
              </div>
            </div>
          </div>
          <div class="text-center">
            <%= f.submit "変更を保存する",class: "btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shops/items/index.html.erb
<div class="container-fluid">
  <div class="form-box">
    <h3 class="page-title"><%= "#{current_shop.shop_name}の商品一覧" %></h3>
    <%= render 'index' %>

app/views/shops/items/new.html.erb
<div class="container-xl">
  <div class="form-box col-lg-8 mx-auto text-center">
    <h3 class="page-title">商品新規登録</h3>
    <%= render 'layouts/errors', model: @item %>
    <%= form_with model: @item,url: shops_items_path,local: true do |f| %>
      <div class="form-group row">
        <div class="col">
        <label>
          <i class="fas fa-images btn">商品画像を選択する</i>
          <%= f.attachment_field :item_image, style: "display: none;" %>
        </label>
        </div>
      </div>
      <div class="form-group row">
        <div class="col">
          <%= f.label "商品名", class:"label-form"%>
        </div>
        <div class="col">
          <%= f.text_field :item_name,placeholder:"青森県産　王林", class:"form-control"%>
        </div>
      </div>
      <div class="form-group row">
        <div class="col">
          <%= f.label "ジャンル", class:"label-form"%>
        </div>
        <div class="col">
          <%= f.select :item_genre, Item.item_genres.keys.to_a, {}, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col">
          <%= f.label "価格（税抜き）", class:"label-form"%>
        </div>
        <div class="col">
          <%= f.number_field :item_price, class:"form-control"%>
        </div>
      </div>
       <div class="form-group row">
        <div class="col">
          <%= f.label "商品説明", class:"label-form"%>
        </div>
        <div class="col">
          <%= f.text_area :item_introduction, class:"form-control"%>
        </div>
      </div>
      <div class="form-group row">
        <div class="col">
          <%= f.label "販売ステータス", class:"label-form"%>
        </div>
        <div class="col">
          <div>
            <%= f.radio_button :sale_status, :true, checked: true %>
            <%= f.label :sale_status, "在庫あり", class: "d-inline-block" %>
          </div>
          <div>
            <%= f.radio_button :sale_status, :false %>
            <%= f.label :sale_status, "品切れ", class: "d-inline-block" %>
          </div>
        </div>
      </div>
      <div class="text-center">
        <%= f.submit "商品を登録する",class:"btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/items/search.html.erb
<div class="container-fluid">
  <div class="form-box">
    <h3 class="page-title">「<%= params[:keyward] %>」を含む商品一覧</h3>
    <%= render 'index' %>

app/views/shops/items/show.html.erb
<div class="container-xl">
  <div class="form-box text-center">
    <h3 class="page-title"><%= @item.item_name%></h3>
    <div class="row">
      <div class="col-md-6">
        <%= attachment_image_tag @item, :item_image, fallback: "no_image.jpeg", class: "lg-image" %>
      </div>
      <div class="col-md-6">
        <div class="info-group row">
          <div class="col-lg-6">
            <label class="info-label">価格</label>
          </div>
          <div class="col-lg-6">
            <%= "#{@item.item_price.to_s(:delimited)}円（税抜き）" %>
          </div>
        </div>
        <div class="info-group row">
          <div class="col-lg-6">
            <label class="info-label">ジャンル</label>
          </div>
          <div class="col-lg-6">
            <%= @item.item_genre %>
          </div>
        </div>
        <div class="info-group row">
          <div class="col-lg-6">
            <label class="info-label">販売ステータス</label>
          </div>
          <div class="col-lg-6">
            <% if @item.sale_status %>
              <p class="text-success">在庫あり</p>
              <% else %>
              <p class="text-danger">品切れ</p>
            <% end %>
          </div>
        </div>
        <div class="info-group row">
          <div class="col-lg-6">
            <label class="info-label">商品説明</label>
          </div>
          <div class="col-lg-6">
            <p><%= @item.item_introduction %></p>
          </div>
        </div>
         <%= link_to "商品を編集する", edit_shops_item_path(@item.id), class: "btn text-center" %>
      </div>
    </div>
  </div>
</div>