config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :shops do
    devise_for :shops, controllers: {
      registrations: 'shops/registrations',
      sessions: 'shops/sessions'
    }
  end

  scope module: :customers do
    devise_for :customers, controllers: {
      registrations: 'customers/registrations',
      sessions: 'customers/sessions'
    }
  end

  namespace :shops do
    get 'orders/search' => 'orders#search'
    resources :orders, only: %i[show index update]
    resources :customers, only: %i[index show]
    resource :mypages, only: %i[show edit update]
    get 'items/search' => 'items#search'
    resources :items, except: [:destroy]
    resources :reviews, only: [:show]
    get 'homes' => 'homes#top'
  end

  scope module: :public do
    root to: 'homes#top'
    get 'shops/search' => 'shops#search'
    resources :shops, only: %i[index show]
    resources :rooms, only: %i[index show create] do
      resources :messages, only: [:create]
    end
    resources :reviews, only: %i[create destroy show]
    resources :favorites, only: %i[index create destroy]
    get 'orders/complete'
    resources :orders, only: %i[new create index show]
    delete 'cart_items/empty'
    resources :cart_items, only: %i[index update destroy create]
    resource :mypages, only: %i[show edit update]
    get 'items/search' => 'items#search'
    resources :items, only: %i[show index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  belongs_to :shop

  validates :amount, presence: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :store_name, presence: true
  validates :store_manager, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :phone_number, presence: true
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :shop
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  attachment :item_image

  def tax
    1.1
  end

  def tax_price
    (item_price * tax).floor
  end

  def self.search(keyward)
    if keyward
      Item.where('item_name LIKE ? OR item_introduction LIKE ?', "%#{keyward}%",
                  "%#{keyward}%")
    else
       Item.none
    end
  end

  def self.select(item_genre, shop_id)
    if item_genre && shop_id
       Item.where(item_genre: item_genre, shop_id: shop_id)
    elsif item_genre
       Item.where(item_genre: item_genre)
    elsif shop_id
       Item.where(shop_id: shop_id)
    else
       Item.all
    end
  end

  belongs_to :shop

  has_many :cart_items
  has_many :order_items

  validates :item_name, presence: true
  validates :item_price, presence: true
  validates :item_genre, presence: true
  validates :item_introduction, presence: true

  enum item_genre: %w[
    食肉
    食肉加工品
    魚介
    魚介加工品
    青果
    野菜
    調味料
    その他
  ]
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :room

  validates :content, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :shop

  has_many :order_items, dependent: :destroy

  validates :total_price, presence: true
  validates :payment, presence: true
  validates :delivery_on, presence: true
  validates :delivery_status, presence: true

  enum delivery_status: %w[
    受注確認前
    発送準備中
    配送中
    納品済み
  ]

  enum payment: %w[
    クレジットカード
    銀行振込
  ]
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  

  validates :price, presence: true
  validates :amount, presence: true
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :customer
  belongs_to :shop

  validates :rate, presence: true
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  belongs_to :customer
  belongs_to :shop

  has_many :messages, dependent: :destroy
end

app/models/shop.rb
# frozen_string_literal: true

class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :shop_image
  
  def self.search(keyward)
    if keyward
      Shop.where('shop_name LIKE ? OR introduction LIKE ?', "%#{keyward}%",
                  "%#{keyward}%")
    else
      Shop.none
    end
  end
  
  def self.select(shop_genre)
    if shop_genre
      Shop.where(shop_genre: shop_genre)
    else
      Shop.all
    end
  end

  has_many :items, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :shop_name, presence: true
  validates :manager, presence: true
  validates :shop_genre, presence: true
  validates :address, presence: true
  validates :postal_code, presence: true
  validates :phone_number, presence: true
  enum shop_genre: [
    '食肉',
    '水産',
    '野菜・青果',
    'その他'
  ]
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/public_controller.rb
# frozen_string_literal: true

class PublicController < ApplicationController
  before_action :authenticate_customer!, except: [:top]
end

app/controllers/shops_controller.rb
# frozen_string_literal: true

class ShopsController < ApplicationController
  before_action :authenticate_shop!, except: [:top]
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/shops/homes_helper.rb
# frozen_string_literal: true

module Shops
  module HomesHelper
  end
end

app/helpers/shops/items_helper.rb
# frozen_string_literal: true

module Shops
  module ItemsHelper
  end
end

app/helpers/shops/mypages_helper.rb
# frozen_string_literal: true

module Shops
  module MypagesHelper
  end
end

app/helpers/shops/orders_helper.rb
# frozen_string_literal: true

module Shops
  module OrdersHelper
  end
end

app/helpers/shops/reviews_helper.rb
# frozen_string_literal: true

module Shops
  module ReviewsHelper
  end
end

app/views/layouts/_errors.html.erb
  <% if model.errors.any? %>
   <div class="errors text-center">
     <ul>
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_header.html.erb
<% if customer_signed_in? %>
  <header class="header">
    <div class="navbar">
      <%= link_to root_path, class: "logo-opacity" do %>
        <%= image_tag 'simple_order_logo.png', class: 'site-logo' %>
      <% end %>
      <div class="right-navbar">
        <ul class="navlists">
          <li class="login-user">ログイン中：<br>
              <%= current_customer.store_name %>様
          </li>
          <%= link_to mypages_path, class: "js-hover" do %>
            <li class="header-link">
              <span>MyPage<br>
                マイページ
              </span>
            </li>
          <% end %>
          <%= link_to items_path, class: "js-hover" do %>
            <li class="header-link">
              <span>Items<br>
                商品一覧
              </span>
            </li>
          <% end %>
          <%= link_to shops_path, class: "js-hover" do %>
            <li class="header-link">
                <span>Shops<br>
                  業者一覧
                </span>
            </li>
          <% end %>
          <%= link_to rooms_path, class: "js-hover" do %>
            <li class="header-link">
              <span>Messages<br>
                メッセージ一覧
              </span>
            </li>
          <% end %>
          <%= link_to favorites_path, class: "js-hover" do %>
            <li class="header-link">
              <span>Favorites<br>
                お気に入り
              </span>
            </li>
          <% end %>
          <%= link_to orders_path, class: "js-hover" do %>
            <li class="header-link">
              <span>Orders<br>
                注文一覧
                </span>
            </li>
          <% end %>
          <%= link_to cart_items_path, class: "js-hover" do %>
            <li class="header-link">
              <i class="fas fa-shopping-cart"></i>
            </li>
          <% end %>
          <%= link_to destroy_customer_session_path, method: :delete, class: "js-hover" do %>
             <li class="header-link">
              <i class="fas fa-sign-out-alt">SignOut</i>
            </li>
          <% end %>
        </ul>
      </div>
      <div id="hm-icon">
        <a class="menu-trigger" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>
    </div>
  </header>
<% elsif shop_signed_in? %>
  <header class="header">
    <div class="navbar">
      <%= link_to shops_homes_path, class: "logo-opacity" do %>
        <%= image_tag 'simple_order_logo.png',class: 'site-logo' %>
      <% end %>
      <div class="right-navbar">
        <ul class="navlists">
          <li class="login-user">ログイン中：<br>
            <%= current_shop.shop_name %>様
          </li>
          <%= link_to shops_mypages_path, class: "js-hover" do %>
            <li class="header-link">
              <span>MyPage<br>
                マイページ
              </span>
            </li>
          <% end %>
          <%= link_to shops_items_path, class: "js-hover" do %>
            <li class="header-link">
              <span>Items<br>
                商品一覧
              </span>
            </li>
          <% end %>
          <%= link_to shops_customers_path, class: "js-hover" do %>
            <li class="header-link">
              <span>Customers<br>
                顧客一覧
              </span>
            </li>
          <% end %>
          <%= link_to rooms_path, class: "js-hover" do %>
            <li class="header-link">
              <span>Messages<br>
                メッセージ一覧
              </span>
            </li>
          <% end %>
          <%= link_to shops_orders_path, class: "js-hover" do %>
            <li class="header-link">
              <span>Orders<br>
                注文一覧
              </span>
            </li>
          <% end %>
          <%= link_to destroy_shop_session_path, method: :delete, class: "js-hover" do %>
            <li class="header-link">
              <i class="fas fa-sign-out-alt"><span>Sign Out</span></i>
            </li>
          <% end %>
        </ul>
      </div>
      <div id="hm-icon">
        <a class="menu-trigger" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>
    </div>
  </header>
<% else %>
  <header class="header">
    <div class="navbar">
      <%= link_to root_path, class: "logo-opacity" do %>
        <%= image_tag 'simple_order_logo.png',class: 'site-logo' %>
      <% end %>
      <div class="right-navbar">
        <ul class="navlists">
          <%= link_to new_customer_session_path, class: "js-hover" do %>
            <li class="header-link"><span>ログイン</span></li>
          <% end %>
          <%= link_to new_customer_registration_path, class: "js-hover" do %>
            <li class="header-link"><span>新規登録</span></li>
          <% end %>
        </ul>
      </div>
      <div id="hm-icon">
        <a class="menu-trigger" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>
    </div>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleOrder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link href="https://fonts.cdnfonts.com/css/butler" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <% if notice %>
      <p class= "alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class= "alert-danger alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <div id="page-top">
      <a href="#"><i class="fas fa-chevron-circle-up"></i></a>
    </div>
  </body>
</html>

app/views/layouts/shop_top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleOrder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link href="https://fonts.cdnfonts.com/css/butler" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header', new_customer_session_path: new_shop_session_path, new_customer_registration_path: new_shop_registration_path %>

    <% if notice %>
      <p class= "alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class= "alert-danger alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <div id="page-top">
      <a href="#"><i class="fas fa-chevron-circle-up"></i></a>
    </div>
  </body>
</html>